### ISSUE TITLE
7.4 I want to be able to give contact tracing powers to other employees so that I can delegate if I am under quarantine

### ISSUE THREAD

**Issue by cessanchez1190** [KirubelMoges/CS3330_Spring21#49]
Criteria:

Given a manager is exposed or tests positive, when they view a list of employees, then they can choose a specific employee and give them temporary managerial access 

Given a manager comes back from quarantining, when they view employees with temporary managerial access, then they may revoke temporary access 

Given an employee has been giventemporary managerial access, when they view others with that access, then they may not add that access to or revoke it from others

**Comment by nicholaswall** [comment]
We allow all users to report contacts with another user and then managers have admin status, managers can make other users managers to enable this temporarily.
